/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      screens: {
        mobile: '480px',
      },
      colors: {
        "secondary-container": "#006781",
        "surface-dim": "#1a0031",
        "on-tertiary-container": "#005c37",
        "error-container": "#a70138",
        "secondary-fixed-dim": "#48d2ff",
        "surface-variant": "#3c0066",
        "on-secondary-fixed": "#003949",
        "surface-tint": "#ff83d1",
        "on-secondary": "#004052",
        "on-surface-variant": "#cd92ff",
        "tertiary-fixed-dim": "#00ef97",
        "on-secondary-container": "#eff9ff",
        "surface-container-low": "#22003d",
        "surface-container-high": "#330058",
        "surface-container": "#2a004a",
        "secondary-dim": "#00c0ee",
        "surface-container-lowest": "#000000",
        "primary-container": "#fa6dc9",
        "surface": "#1a0031",
        "primary-dim": "#f66ac6",
        "outline": "#9e4be3",
        "on-error-container": "#ffb2b9",
        "tertiary-container": "#0affa1",
        "primary": "#ff83d1",
        "on-tertiary-fixed": "#004729",
        "on-primary-container": "#480036",
        "primary-fixed-dim": "#ed62be",
        "on-error": "#490013",
        "on-tertiary": "#00663d",
        "outline-variant": "#6c02b1",
        "on-tertiary-fixed-variant": "#00673e",
        "on-primary": "#5d0046",
        "on-primary-fixed": "#020001",
        "surface-container-highest": "#3c0066",
        "tertiary-fixed": "#0affa1",
        "background": "#1a0031",
        "inverse-surface": "#fff7fd",
        "primary-fixed": "#fd6fcc",
        "secondary-fixed": "#86ddff",
        "inverse-on-surface": "#7b21c0",
        "error-dim": "#d73357",
        "error": "#ff6e84",
        "tertiary-dim": "#00ef97",
        "tertiary": "#b1ffcd",
        "on-secondary-fixed-variant": "#00586f",
        "inverse-primary": "#a82683",
        "on-background": "#f3deff",
        "on-surface": "#f3deff",
        "secondary": "#0fceff",
        "surface-bright": "#450074",
        "on-primary-fixed-variant": "#5d0046"
      },
      fontFamily: {
        headline: ["Space Grotesk"],
        body: ["Plus Jakarta Sans"],
        label: ["Space Grotesk"]
      }
    },
  },
  plugins: [],
}
